name: Pester Tests on Ubuntu
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          pwd
          Test-Path ".\TestResults"
          if(-not (test-path ".\TestResults")) {"Making new directory"; new-item -ItemType Directory "TestResults"}
          Invoke-Pester Test.ps1 -Passthru -OutputFile ".\TestResults\TestResults.xml" -OutputFormat NUnitXml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TestResults/*.xml
            TestResults/*.trx
            TestResults/*.json
