name: Pester Tests on Ubuntu
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Import the Module from src
        shell: pwsh
        run: Import-Module -Name './src/Okta.PowerShell' -Verbose
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          if(-not (test-path ".\TestResults")) {"Making new directory"; new-item -ItemType Directory "TestResults"}
          $pesterConfig = New-PesterConfiguration
          $pesterConfig.TestResult.OutputPath = "./TestResults/TestResults.xml"
          $pesterConfig.TestResult.OutputFormat = "NUnitXml"
          $pesterConfig.TestResult.Enabled = $true
          Invoke-Pester -Passthru -Configuration $pesterConfiguration
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pester-results
          # This does not use the working-directory from defaults so must use **
          path: '**/TestResults'
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TestResults/*.xml
            TestResults/*.trx
            TestResults/*.json
